services:
  RabbitMQ:
    image: rabbitmq:4.2-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  Redis:
    image: redis:8.6-alpine
    ports:
      - "6379:6379"

  Jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"