# syntax=docker/dockerfile:1

FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server cmd/server/main.go

FROM alpine:latest AS runner
WORKDIR /app
COPY --from=build /app/server /app/server
RUN chmod +x /app/server
EXPOSE 50051
ENTRYPOINT [ "/app/server" ]