// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/chess_match.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player int32

const (
	Player_VALUE_UNSPECIFIED Player = 0
	Player_WHITE             Player = 1
	Player_BLACK             Player = 2
)

// Enum value maps for Player.
var (
	Player_name = map[int32]string{
		0: "VALUE_UNSPECIFIED",
		1: "WHITE",
		2: "BLACK",
	}
	Player_value = map[string]int32{
		"VALUE_UNSPECIFIED": 0,
		"WHITE":             1,
		"BLACK":             2,
	}
)

func (x Player) Enum() *Player {
	p := new(Player)
	*p = x
	return p
}

func (x Player) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Player) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chess_match_proto_enumTypes[0].Descriptor()
}

func (Player) Type() protoreflect.EnumType {
	return &file_proto_chess_match_proto_enumTypes[0]
}

func (x Player) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Player.Descriptor instead.
func (Player) EnumDescriptor() ([]byte, []int) {
	return file_proto_chess_match_proto_rawDescGZIP(), []int{0}
}

type Move struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UMID              int32                  `protobuf:"varint,1,opt,name=UMID,proto3" json:"UMID,omitempty"`
	CurrentPlayer     Player                 `protobuf:"varint,2,opt,name=current_player,json=currentPlayer,proto3,enum=Player" json:"current_player,omitempty"`
	StartingSquare    string                 `protobuf:"bytes,3,opt,name=starting_square,json=startingSquare,proto3" json:"starting_square,omitempty"`
	DestinationSquare string                 `protobuf:"bytes,4,opt,name=destination_square,json=destinationSquare,proto3" json:"destination_square,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_proto_chess_match_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chess_match_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_proto_chess_match_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetUMID() int32 {
	if x != nil {
		return x.UMID
	}
	return 0
}

func (x *Move) GetCurrentPlayer() Player {
	if x != nil {
		return x.CurrentPlayer
	}
	return Player_VALUE_UNSPECIFIED
}

func (x *Move) GetStartingSquare() string {
	if x != nil {
		return x.StartingSquare
	}
	return ""
}

func (x *Move) GetDestinationSquare() string {
	if x != nil {
		return x.DestinationSquare
	}
	return ""
}

var File_proto_chess_match_proto protoreflect.FileDescriptor

const file_proto_chess_match_proto_rawDesc = "" +
	"\n" +
	"\x17proto/chess_match.proto\"\xa2\x01\n" +
	"\x04Move\x12\x12\n" +
	"\x04UMID\x18\x01 \x01(\x05R\x04UMID\x12.\n" +
	"\x0ecurrent_player\x18\x02 \x01(\x0e2\a.PlayerR\rcurrentPlayer\x12'\n" +
	"\x0fstarting_square\x18\x03 \x01(\tR\x0estartingSquare\x12-\n" +
	"\x12destination_square\x18\x04 \x01(\tR\x11destinationSquare*5\n" +
	"\x06Player\x12\x15\n" +
	"\x11VALUE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05WHITE\x10\x01\x12\t\n" +
	"\x05BLACK\x10\x02B8Z6github.com/1saswata/chess-broadcast-engine/internal/pbb\x06proto3"

var (
	file_proto_chess_match_proto_rawDescOnce sync.Once
	file_proto_chess_match_proto_rawDescData []byte
)

func file_proto_chess_match_proto_rawDescGZIP() []byte {
	file_proto_chess_match_proto_rawDescOnce.Do(func() {
		file_proto_chess_match_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chess_match_proto_rawDesc), len(file_proto_chess_match_proto_rawDesc)))
	})
	return file_proto_chess_match_proto_rawDescData
}

var file_proto_chess_match_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chess_match_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_chess_match_proto_goTypes = []any{
	(Player)(0),  // 0: Player
	(*Move)(nil), // 1: Move
}
var file_proto_chess_match_proto_depIdxs = []int32{
	0, // 0: Move.current_player:type_name -> Player
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_chess_match_proto_init() }
func file_proto_chess_match_proto_init() {
	if File_proto_chess_match_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chess_match_proto_rawDesc), len(file_proto_chess_match_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_chess_match_proto_goTypes,
		DependencyIndexes: file_proto_chess_match_proto_depIdxs,
		EnumInfos:         file_proto_chess_match_proto_enumTypes,
		MessageInfos:      file_proto_chess_match_proto_msgTypes,
	}.Build()
	File_proto_chess_match_proto = out.File
	file_proto_chess_match_proto_goTypes = nil
	file_proto_chess_match_proto_depIdxs = nil
}
